let usCities = {
	"KABI": "Abilene",
	"KALB": "Albany",
	"KABQ": "Albuquerque",
	"KAMA": "Amarillo",
	"PANC": "Anchorage",
	"KAVL": "Asheville",
	"KASE": "Aspen",
	"KATL": "Atlanta",
	"KACY": "Atlantic City",
	"KAUS": "Austin",
	"KBWI": "Baltimore",
	"KBIL": "Billings",
	"KBHM": "Birmingham",
	"KBIS": "Bismarck",
	"KBOI": "Boise",
	"KBOS": "Boston",
	"KBRO": "Brownsville",
	"KBUF": "Buffalo",
	"KBTV": "Burlington",
	"KCLT": "Charlotte",
	"KCHS": "Charlstn SC",
	"KCRW": "Charlstn WV",
	"KCHA": "Chattanooga",
	"41.14,-104.820278": "Cheyenne",
	"KCVG": "Cincinnati",
	"KCLE": "Cleveland",
	"KCOS": "Colo. Spgs",
	"KCOU": "Columbia MO",
	"KCAE": "Columbia SC",
	"KCMH": "Columbus",
	"KCON": "Concord",
	"KCRP": "Crps Christi",
	"KDFW": "Dallas",
	"KDAB": "Daytona Bch.",
	"KDEN": "Denver",
	"KDLH": "Duluth",
	"KELP": "El Paso",
	"PAFA": "Fairbanks",
	"KFAR": "Fargo",
	"KFLG": "Flagstaff",
	"KRSW": "Fort Myers",
	"KFSM": "Fort Smith",
	"KFAT": "Fresno",
	"KGJT": "Grand Junc.",
	"KGTF": "Great Falls",
	"KMDT": "Harrisburg",
	"KBDL": "Hartford",
	"KHLN": "Helena",
	"PHNL": "Honolulu",
	"KIAH": "Houston",
	"KINL": "Int'l Falls",
	"KJAN": "Jackson",
	"KJAX": "Jacksonville",
	"PAJN": "Juneau",
	"KMCI": "Kansas City",
	"KLAS": "Las Vegas",
	"KLEX": "Lexington",
	"KLNK": "Lincoln",
	"KLIT": "Little Rock",
	"KLAX": "Los Angeles",
	"KSDF": "Louisville",
	"KMCN": "Macon",
	"KMEM": "Memphis",
	"KMIA": "Miami",
	"KMSP": "Minneapolis",
	"KMOB": "Mobile",
	"KMGM": "Montgomery",
	"KBNA": "Nashville",
	"KMSY": "New Orleans",
	"KJFK": "New York",
	"KORF": "Norfolk",
	"KOKC": "Okla. City",
	"KOMA": "Omaha",
	"KMCO": "Orlando",
	"26.705621,-80.036430": "Palm Beach",
	"KPSP": "Palm Springs",
	"KPHL": "Philadelphia",
	"KPHX": "Phoenix",
	"KPIT": "Pittsburgh",
	"KPWM": "Portland, ME",
	"KPDX": "Portland, OR",
	"KPVD": "Providence",
	"KRDU": "Raleigh",
	"KRAP": "Rapid City",
	"KRNO": "Reno",
	"KRIC": "Richmond",
	"KRST": "Rochester",
	"KSMF": "Sacramento",
	"44.939167,-123.039444": "Salem, Ore.",
	"KSLC": "Salt Lake City",
	"KSAT": "San Antonio",
	"KSAN": "San Diego",
	"KSFO": "San Francisco",
	"TJSJ": "San Juan",
	"KSAF": "Santa Fe",
	"KSAV": "Savannah",
	"KSEA": "Seattle",
	"KSHV": "Shreveport",
	"KFSD": "Sioux Falls",
	"KGEG": "Spokane",
	"KSTL": "St. Louis",
	"KSYR": "Syracuse",
	"KTLH": "Tallahassee",
	"KTPA": "Tampa",
	"39.055833,-95.689444": "Topeka",
	"KTUS": "Tucson",
	"KTUL": "Tulsa",
	"KIAD": "Washington",
	"KICT": "Wichita",
	"KAVP": "Wilkes Barre",
	"KNYL": "Yuma"
};