/* https://airportcodes.io/en/ */

let worldCities = {
	"MMAA": "Acapulco",
	"DAAG": "Algiers",
	"EHAM": "Amsterdam",
	"LTAC": "Ankara",
	"LGAV": "Athens",
	"NZAA": "Auckland",
	"ORBI": "Baghdad",
	"VTBS": "Bangkok",
	"TBPB": "Barbados",
	"LEBL": "Barcelona",
	"ZBAA": "Beijing",
	"OLBA": "Beirut",
	"EDDB": "Berlin",
	"TXKF": "Bermuda",
	"SKBO": "Bogota",
	"EBBR": "Brussels",
	"LROP": "Bucharest",
	"LHBP": "Budapest",
	"SAEZ": "Buenos Aires",
	"HECA": "Cairo",
	"MMUN": "Cancun",
	"SVMI": "Caracas",
	"GMMN": "Casablanca",
	"EKCH": "Copenhagen",
	"EIDW": "Dublin",
	"CYEG": "Edmonton",
	"EDDF": "Frankfurt",
	"LSGG": "Geneva",
	"MMGL": "Guadalajara",
	"MUHA": "Havana",
	"EFHK": "Helsinki",
	"VHHH": "Hong Kong",
	"LTBA": "Istanbul",
	"LLJR": "Jerusalem",
	"FAOR": "Johannesburg",
	"OAKB": "Kabul",
	"MKJP": "Kingston",
	"UKKK": "Kyiv",
	"SPJC": "Lima",
	"LPPT": "Lisbon",
	"EGLL": "London",
	"LEMD": "Madrid",
	"RPLL": "Manila",
	"MMMX": "Mexico City",
	"MMMY": "Monterrey",
	"CYUL": "Montreal",
	"UUEE": "Moscow",
	"EDDM": "Munich",
	"HKJK": "Nairobi",
	"MYNN": "Nassau",
	"VIDP": "New Delhi",
	"ENGM": "Oslo",
	"CYOW": "Ottawa",
	"MPTO": "Panama City",
	"LFPG": "Paris",
	"LKPR": "Prague",
	"SBGL": "Rio de Janeiro",
	"OERK": "Riyadh",
	"LIRF": "Rome",
	"SCEL": "Santiago",
	"RKSI": "Seoul",
	"WSSS": "Singapore",
	"LBSF": "Sofia", 
	"ESSA": "Stockholm",
	"YSSY": "Sydney",
	"RCTP": "Taipei",
	"OIIE": "Tehran",
	"RJTT": "Tokyo",
	"CYYZ": "Toronto",
	"TTPP": "Trinidad",
	"CYVR": "Vancouver",
	"LOWW": "Vienna",
	"EPWA": "Warsaw",
	"CYWG": "Winnipeg"
};